version: '3.7'
services:
  web:
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=students
    ports:
      - "5431:5432"   
